# symfonycasts_reset_password:
#     # Replace symfonycasts.reset_password.fake_request_repository with the full
#     # namespace of the password reset request repository after it has been created.
#     # i.e. App\Repository\ResetPasswordRequestRepository
#     request_password_repository: symfonycasts.reset_password.fake_request_repository
# # reset_password:
# #     token:
# #         ttl: 86400 # Durée de validité du token en secondes (par exemple, 86400 secondes = 24 heures)
# #         route:
# #             name: app_reset_password_reset # Nom de la route utilisée pour réinitialiser le mot de passe
# #         parameter_name: token