controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

products_by_category:
    path: /produits-de-la-categorie/{categoryId}
    controller: 'App\Controller\HomeController::productsByCategory'


app_add_to_cart:
    path: '/panier/ajout/{productId}/{count}'
    controller: 'App\Controller\CartController::addToCart'

app_product_by_slug:
    path: '/produit/{slug}'
    controller: 'App\Controller\HomeController::showProductBySlug'


add_to_cart:
    path: '/panier/ajout/{productId}'
    controller: 'App\Controller\CartController::addToCart'


# app_reset_password:
#     path: /reset/{token}
#     controller: App\Controller\ResetPasswordController::reset

# app_forgot_password_request:
#     path: /reset-password
#     controller: App\Controller\ResetPasswordController::request

# products_for_slider:
#     path: '/products-for-slider/{slider_id}'
#     controller: 'App\Controller\HomeController::productsForSlider'
#     requirements:
#         slider_id: '\d+'  
#     methods: ['GET']
